name: 'Checkout'
description: 'Checkout repository code'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        # We're already in the workspace in GitHub Actions
        # Just need to make sure we have the right code
        
        echo "Current directory: $(pwd)"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Ref: $GITHUB_REF"
        echo "SHA: $GITHUB_SHA"
        
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Fetch all history and tags
        git fetch --prune --unshallow || git fetch --prune
        
        # Checkout the specific ref if provided
        if [ -n "$GITHUB_REF" ]; then
          git checkout $GITHUB_REF || git checkout $GITHUB_SHA || true
        fi
        
        echo "Repository checked out successfully"
