name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make curl unzip

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc make curl unzip || true

      - name: Build dirdoc on Linux/macOS
        if: runner.os != 'Windows'
        run: make all
        shell: bash

      - name: Run tests on Linux/macOS
        if: runner.os != 'Windows'
        run: make test
        shell: bash

      - name: Clean up build artifacts
        run: make clean
        shell: bash
