name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y build-essential make curl unzip || true

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install make curl unzip || true

      - name: Build dirdoc on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          echo "Building dirdoc..."
          make all
          echo "Build completed successfully!"
          ls -la build/
        shell: bash

      - name: Run tests on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          echo "Running tests..."
          make test
          echo "Tests completed successfully!"
        shell: bash

      - name: Clean up build artifacts
        run: make clean
        shell: bash
