name: Enforce Version Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required version label
        id: check-labels
        run: |
          LABELS="${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "Raw Labels: $LABELS"
          
          # Print for debugging
          echo "Checking for major label..."
          echo "Label contains 'major'? $(echo "$LABELS" | grep -q "major" && echo "YES" || echo "NO")"
          echo "Checking for minor label..."
          echo "Label contains 'minor'? $(echo "$LABELS" | grep -q "minor" && echo "YES" || echo "NO")"
          echo "Checking for patch label..."
          echo "Label contains 'patch'? $(echo "$LABELS" | grep -q "patch" && echo "YES" || echo "NO")"
          
          # Simpler detection method
          if echo "$LABELS" | grep -q "major"; then
            MAJOR_LABEL="major"
            echo "Found major label"
          else
            MAJOR_LABEL=""
          fi
          
          if echo "$LABELS" | grep -q "minor"; then
            MINOR_LABEL="minor"
            echo "Found minor label"
          else
            MINOR_LABEL=""
          fi
          
          if echo "$LABELS" | grep -q "patch"; then
            PATCH_LABEL="patch"
            echo "Found patch label"
          else
            PATCH_LABEL=""
          fi
          
          VERSION_LABELS_COUNT=0
          if [ ! -z "$MAJOR_LABEL" ]; then ((VERSION_LABELS_COUNT++)); fi
          if [ ! -z "$MINOR_LABEL" ]; then ((VERSION_LABELS_COUNT++)); fi
          if [ ! -z "$PATCH_LABEL" ]; then ((VERSION_LABELS_COUNT++)); fi
          
          if [ $VERSION_LABELS_COUNT -eq 0 ]; then
            echo "❌ Error: No version label found"
            echo "This PR requires exactly one version label: 'major', 'minor', or 'patch'"
            exit 1
          elif [ $VERSION_LABELS_COUNT -gt 1 ]; then
            echo "❌ Error: Multiple version labels found"
            echo "This PR should have exactly one version label: 'major', 'minor', or 'patch'"
            exit 1
          else
            echo "✅ Version label check passed"
          fi
