name: Build and Release dirdoc

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update || true
          apt-get install -y build-essential make curl unzip || true

      - name: Build dirdoc
        run: make all
        shell: bash

      - name: Copy binary to root directory
        run: |
          cp build/dirdoc ./dirdoc
          chmod +x ./dirdoc

  release:
    name: Create Release and Upload Artifact
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # No need to download artifact as we'll use the binary from the build step

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: |
            Automated release of dirdoc binary.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Windows executable copy
        run: |
          chmod +x dirdoc
          cp dirdoc dirdoc.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dirdoc
            dirdoc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
