name: Build and Release dirdoc

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update || true
          apt-get install -y build-essential make curl unzip || true

      - name: Build dirdoc
        run: make all
        shell: bash

      - name: Create Windows executable copy
        run: |
          cp build/dirdoc ./dirdoc
          chmod +x ./dirdoc
          cp dirdoc dirdoc.exe
          # Verify files exist and have proper permissions
          ls -la dirdoc*

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: |
            Automated release of dirdoc binary.
          files: |
            dirdoc
            dirdoc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Skip GitHub Release (Local Testing)
        if: env.ACT == 'true'
        run: |
          echo "Skipping GitHub Release step when running locally with act"
          echo "The binaries have been created successfully:"
          ls -la dirdoc*
